config/routes.rb
MasteryProject::Application.routes.draw do

  root to: "poems#new"

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"

  resources :poems
  resources :users
  resources :sessions

  namespace :api do
    resources :poems, only: [:update, :index], defaults: { format: "JSON" }
    resources :words, only: [:show], defaults: { format: "JSON" }
  end
end

app/models/poem.rb
class Poem < ActiveRecord::Base
  attr_accessible :original_text, :poem_text, :max_lines, :max_syllables, :title, :pic, :public_poem

  belongs_to :user

  validates :original_text, presence: true
  validates :max_lines, :numericality =>
                            {:greater_than => 0, :message => "You must have at least one line in a stanza" }
  validates :max_syllables, :numericality =>
                                {:greater_than => 0, :message => "You must have at least one syllable in a line" }

  def replace(index, word)
    edit = poem_text.split(" ")
    punctuation = edit[index].scan(/\W+\z/).pop
    if punctuation == nil
      edit[index] = word
    else
      edit[index] = word + punctuation
    end
    update_attributes(poem_text: edit.join(" "))
  end

  def verse_form
    syllable_lines.each_slice(max_lines).to_a
  end

private
  def words_with_punctuation
    poem_text.split(" ")
  end

  def syllable_lines
    # transform words_with_punctuation into an array of lines with a certain number of syllables

    # iterate over the array, and join words together until
    current_line = []
    all_lines = []
    line_syllables = 0

    words_with_punctuation.each do |word|
      clean_word = Word.clean(word)
      word_sylls = Word.syllables(clean_word)

      if (line_syllables + word_sylls) <= max_syllables
        line_syllables += word_sylls
        current_line << word

        is_last_word({word: word,
                      line: current_line,
                     lines: all_lines})

      else
        all_lines << current_line.join(" ")
        current_line = [word]
        line_syllables = word_sylls

        is_last_word({word: word,
                      line: current_line,
                     lines: all_lines})

      end
    end

    return all_lines
  end

  def is_last_word(args)
    if args[:word] == words_with_punctuation.last
      args[:lines] << args[:line].join(" ")
    end
  end
end

# def lines_array(dirty_words_array)
#     current_line = []
#     all_lines = []
#     line_syllables = 0

#     dirty_words_array.each do |word|
#       clean_word = Word.clean(word)
#       word_sylls = Word.syllables(clean_word)

#       if (line_syllables + word_sylls) <= max_syllables
#         line_syllables += word_sylls
#         current_line << word

#         if word == dirty_words_array.last
#           all_lines << current_line.join(" ")
#         end

#       else
#         all_lines << current_line.join(" ")
#         current_line = [word]
#         line_syllables = word_sylls

#         if word == dirty_words_array.last
#           all_lines << current_line.join(" ")
#         end

#       end
#     end

#     return all_lines
#   end

app/controllers/api/poems_controller.rb
class Api::PoemsController < ApplicationController

  def update
    poem = Poem.find(params[:id])
    poem.replace(params[:oldWord].to_i, params[:newWord])
    poem.save

    respond_to do |format|
      format.json { render json: @payload }
    end
  end
end

  # def index
  #   @poems = Poem.where(public_poem: true).where("title like ?", "%#{params[:search]}%")
  #   @search = params[:search]
  #   @payload = {}
  #   @payload[:poems] = []
  #   @poems.each do |poem|

  #     @payload[:poems] << {   id: poem.id,
  #                            pic: poem.pic,
  #                          title: poem.title   }
  #   end
  #   @payload[:search] = @search

  #   respond_to do |format|
  #     format.json { render json: @payload }
  #   end
  # end

# makes new request for poems matching each search instead of just 'hiding' those that don't

app/controllers/poems_controller.rb
class PoemsController < ApplicationController
  before_filter :edit_poem_protection, :only => [:edit, :update]
  before_filter :show_poem_protection, :only => [:show]

  def new
    @poem = Poem.new
  end

  def create
    @poem = Poem.new(params[:poem])
    @poem.poem_text ||= @poem.original_text
    if current_user
      @poem.user_id = current_user.id
    end

    if @poem.save
      redirect_to edit_poem_path(@poem)
    else
      flash[:error] = "Please try again."
      redirect_to new_poem_path
    end
  end

  def edit
    @poem = Poem.find(params[:id])

    session[:current_poem] = @poem.id
    if @poem.user_id == nil && current_user
      current_user.poems << @poem
    end
  end

  def update
    @poem = Poem.find(params[:id])
    @poem.assign_attributes(params[:poem])

    if @poem.save
      redirect_to edit_poem_path(@poem), notice: "Updated!"
    else
      redirect_to edit_poem_path(@poem), error: "Invalid Attributes"
    end
    # respond_to do |format|
    #   format.html { redirect_to edit_poem_path(@poem) }
    #   format.js
    # end
  end

  def index
    if params[:search]
      @poems = Poem.where(public_poem: true).where("title like ?", "%#{params[:search]}%").paginate(:page => params[:page], :per_page => 30)
      @search = params[:search]
      # fail
    else
      @poems = Poem.where(public_poem: true).paginate(:page => params[:page], :per_page => 30)
    end
  end

  def show
    @poem = Poem.find(params[:id])
  end
end

app/views/poems/_poem.html.erb
<div class="poem-pic text-center" data-title="<%= poem.title %>">
  <%= link_to image_tag(poem.pic), poem_path(poem.id) %>
  <div class="poem-title-link">
    <%= link_to "#{poem.title}", poem_path(poem.id), class: "poem-title-link" %>
  </div>
</div>

app/views/poems/_poem_text.html.erb
<h3 class="text-center"><%=@poem.title.titleize%></h3>
<% word_position = 0 %>
  <% @poem.verse_form.each do |stanza| %>
    <table style="width:100%">
      <% stanza.each do |line| %>
        <tr>
          <td class='line'>
              <% line.split.each do |word|%>

                <% pieces = Word.text(word) %>

                  <%= pieces[0] %><span class='word' id='<%= word_position %>'><%=pieces[1]%></span><%= pieces[2] %>

                <% word_position += 1 %>
              <% end %>
            <span class="pull-right"><%= Word.syllables(line) %></span>
          </td>
        </tr>
      <% end %>
      <hr/>
    </table>
  <% end %>
<hr/>

app/views/poems/_verse_form_options.html.erb
<%= simple_form_for @poem do |f| %>
  <%= f.input :public_poem, as: :select, label: "Public", input_html: { value: @poem.public_poem } %>
  <%= f.input :pic, label: "Picture URL", input_html: { value: @poem.pic } %>
  <%= f.input :title, input_html: { value: @poem.title } %>
  <%= f.input :max_lines, input_html: { value: @poem.max_lines } %>
  <%= f.input :max_syllables, input_html: { value: @poem.max_syllables } %>
  <%= f.submit "Update", class: "btn btn-info" %>
<% end %>



<div id="tool-buttons">
  <button class="btn tool-buttons" type="button" id="synonyms">Synonyms</button><br/>
  <button class="btn tool-buttons" type="button" id="rhyme-with">Rhyme-with</button><br/>
  <button class="btn tool-buttons" type="button" id="replace-with">Replace</button>
</div>

<div class="d-box" id="replacement-form" title="Replace">
  <div class="input-append">
    <input class="span2" id="replacement-text" type="text">
    <button class="btn" type="button" id="replace-button">Replace!</button>
  </div>
</div>

<div class="d-box" id="synonym-box" title="Synonyms">
  <div class="progress progress-striped active">
    <div class="bar" style="width: 100%;"></div>
  </div>
  <ul class="synonyms"></ul>
</div>

<div class="d-box" id="rhyme-box" title="Rhymes">
  <div class="progress progress-striped active">
    <div class="bar" style="width: 100%;"></div>
  </div>
  <ul class="rhymes"></ul>
</div>

<div id="popover-title">
  <span class="word-spelling"></span>
  <span class="pull-right" id="close-popover"><img src="http://www.iconattitude.com/icons/open_icon_library/actions/png/256/window-close.png" height="20" width="20"></span>
</div>

app/views/poems/edit.html.erb
<div class="span5 offset1" id="original-text">
  <h3 class="text-center">Original Text</h3>
  <hr/>
  <%= @poem.original_text %>
  <br/>
  <br/>
  <br/>
  <br/>
  <%= render partial: "verse_form_options" %>
</div>

<div class="poem-id" id="<%=@poem.id%>"></div>

<div class='span5 offset1' id='poem-text'>

  <%= render partial: "poem_text" %>
</div>

app/views/poems/index.html.erb
<div class="span4">
  <div id="search-for-poems">

    <%= form_tag poems_path, :class => "form-search", :method => 'get' do %>
      <p>
        <%= text_field_tag :search, params[:search], :class => "input-medium search-query" %>
        <%= submit_tag "Search", :name => nil, :class => "btn btn-primary" %>
      </p>
    <% end %>

    <% if @search %>
      Search for <span id="search-results"><%=@search%></span>: <%= @poems.count %> found
    <% end %>
    <%= link_to "Browse All", poems_path%>
  </div>
</div>

<div class="text-center span7 offset1">
  <h3>Public Poems</h3>
  <% if @poems.present? %>
    <div class="masonry-container">
      <%= render partial: "poems/poem", collection: @poems %>
    </div>
  <% else %>
    Sorry, no poems about <span id="search-results"><%=@search%></span> were found, please try again
  <% end %>
</div>

<%= will_paginate @poems %>


<!--     <form class="form-search" action="/poems" method="get">
      <input type="text" class="input-medium search-query" name="search" id="poem-index-search-form">
      <button type="submit" value="search" class="btn btn-primary" id="search-poem-index">Search</button>
    </form>
 -->

app/views/poems/new.html.erb
<div class="row">
  <div class="form text-center">
    <h1>Enter Prose!</h1>
    <%= simple_form_for @poem do |f| %>
      <%= f.input :title, label: false %>
      <%= f.text_area :original_text, placeholder: "Enter original text here..." %>
  </div>
</div>

<div class="row">
  <div class="text-center">
      <%= f.button :submit, "Begin!", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/poems/show.html.erb
<div class="span5 offset1" id="original-text">
  <h3 class="text-center">Original Text</h3>
  <hr/>
  <%= @poem.original_text %>
</div>
<div class='span5 offset1 text-center' id='poem-text'>
  <h3><%=@poem.title.titleize%></h3>
  <% @poem.verse_form.each do |stanza| %>
    <table style="width:100%" class="text-center">
      <% stanza.each do |line| %>
        <tr>
          <td>
              <%= line %>
          </td>
        </tr>
      <% end %>
      <hr/>
    </table>
  <% end %>
  <hr/>
</div>

app/views/poems/update.js.erb
$('#poem-text').html("<%= j render('poem_text') %>");