config/routes.rb
MasteryProject::Application.routes.draw do

  root to: "poems#new"

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"

  resources :poems
  resources :users
  resources :sessions

  namespace :api do
    resources :poems, only: [:update, :index], defaults: { format: "JSON" }
    resources :words, only: [:show], defaults: { format: "JSON" }
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  attr_accessible :username, :email, :password, :password_confirmation

  has_many :poems

  validates :email, presence: true, uniqueness: true,
            format: { with: /\A[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]+\z/ }
  validates :password, presence: true
  validates_length_of :password, :minimum => 8, :message => "password must be at least 8 characters long", :if => :password
  validates_confirmation_of :password, :message => "should match confirmation", :if => :password
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_login, :only => [:edit, :update, :show]
  before_filter :authenticate, :only => [:edit, :update, :show]

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])

    if @user.save
      auto_login(@user)
      if session[:current_poem]
        flash[:notice] = "Account created! Welcome #{@user.email}!"
        redirect_to edit_poem_path(session[:current_poem])
      else
        flash[:notice] = "Account created! Welcome #{@user.email}!"
        redirect_to root_path
      end
    else
      flash[:error] = "Invalid email or password."
      redirect_to signup_path
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(params[:user])
      redirect_back_or_to root_path, notice: "Account updated!"
    else
      flash[:error] = "Invalid email or password"
      redirect_to edit_user_path(@user)
    end
  end

  def show
    @user = User.includes(:poems).find(params[:id])
    @poems = @user.poems
    if params[:public_poem]
      params[:public_poem] == "true" ? @heading = "Public poems" : @heading = "Private poems"
    else
      @heading = "All poems"
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="text-center auth-form">
  <% if current_user == new_user_path %>
    <h3>Create Account</h3>
  <% else %>
    <h3>Update Account</h3>
  <% end %>
  <%= simple_form_for @user do |f| %>
    <%= f.input :email, label: false, placeholder: "email" %>
    <%= f.input :password, label: false, placeholder: "password" %>
    <%= f.input :password_confirmation, required: true, label: false, placeholder: "password confirmation" %>
    <%= f.button :submit, "Submit", class: "btn btn-primary"  %>
  <% end %>
</div>

app/views/users/_home_side_menu.html.erb
<div id="home-side-menu">
  <h3>My Poems</h3>
  <ul>
    <li><%= link_to "All poems","#", id: "all-poems" %></li>
    <li><%= link_to "Public poems","#", id: "public-poems" %></li>
    <li><%= link_to "Private poems","#", id: "private-poems" %></li>
    <li><%= link_to "Create new poem", "/" %></li>
  </ul>
</div>

app/views/users/edit.html.erb
<%= render partial: "form" %>

app/views/users/new.html.erb
<div class="text-center auth-form">
  <h3>Create Account</h3>
  <%= simple_form_for @user do |f| %>
    <%= f.input :email, label: false, placeholder: "email" %>
    <%= f.input :password, label: false, placeholder: "password" %>
    <%= f.input :password_confirmation, required: true, label: false, placeholder: "password confirmation" %>
    <%= f.button :submit, "Create Account", class: "btn btn-primary"  %>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="span3 offset1">
  <%= render partial: "home_side_menu" %>
</div>

<div class="span7 offset1">
  <% if @user.poems == [] %>
    <div class="text-center">
      <h3>You have no written any poems yet</h3>
      <%= link_to "Create Poem", new_poem_path %>
    </div>
  <% else %>
  <h3 class="text-center"><%=@heading%></h3>
    <div class="masonry-container">
        <% @poems.each do |poem| %>

          <% if poem.pic %>
            <div class=<%="public-#{poem.public_poem}"%>>
              <div class="poem-pic text-center">
                <%= link_to image_tag(poem.pic), edit_poem_path(poem.id) %>
                <div class="poem-title-link">
                  <%= link_to "#{poem.title}", edit_poem_path(poem.id), class: "poem-title-link" %>
                </div>
              </div>
            </div>
          <% else %>
              <div class="poem-pic text-center poem-title-link">
                <%= link_to "#{poem.title}", edit_poem_path(poem.id), class: "poem-title-link" %>
              </div>
          <% end %>

        <% end %>
    </div>
  <% end %>
</div>